# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://kerrycanoeclub.com
title: Kerry Canoe Club
email: kerrycanoeclubkillorglin@gmail.com
author: Barry Fitzgerald
description: > # "Kerry's foremost canoe club
copyright: 'Copyright &copy; 2020 Kerry Canoe Club. All Rights Reserved.'
credits: 'Credits: BF'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/kerrycanoeclub/
    icon: facebook
  - title: email
    url: mailto:kerrycanoeclubkillorglin@gmail.com
    icon: envelope
